{% set name = "dagster_postgres" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 6f22b1ba8f5d4adfb45d4d3f0c139d3eadc37c5b879ecac91307be269c810fa5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*
    - psycopg2

test:
  imports:
    - dagster_postgres

about:
  home: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-postgres
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A Dagster integration for postgres

extra:
  recipe-maintainers:
    - conda-forge/dagster
